In [1]:
# Import libraries and modules
import numpy as np
import pandas as pd
import matplotlib.pyplot as plot
from pandas import DataFrame, Series

# Enable inline plotting
%matplotlib inline

In [2]:
# Create the initial set of days and miles
days = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
#miles = [55, 65, 70, 62, 45, 26, 48, 56, 98, 50]
# create an array for miles
miles = np.array([55, 65, 70, 62, 45, 26, 48, 56, 98, 50])
#total = [0 for i in range(10)]
total = np.array([0]*10)
days, miles, total

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([55, 65, 70, 62, 45, 26, 48, 56, 98, 50]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

In [3]:
# Zip the lists together and create a new data set
TripDataSet = list(zip(days,miles,total))
TripDataSet

[(1, 55, 0),
 (2, 65, 0),
 (3, 70, 0),
 (4, 62, 0),
 (5, 45, 0),
 (6, 26, 0),
 (7, 48, 0),
 (8, 56, 0),
 (9, 98, 0),
 (10, 50, 0)]

In [4]:
# Create the dataframe and label both columns
df = pd.DataFrame(data = TripDataSet, columns=['Days', 'Miles', 'Total Miles'])
df

Days  Miles  Total Miles
0     1     55            0
1     2     65            0
2     3     70            0
3     4     62            0
4     5     45            0
5     6     26            0
6     7     48            0
7     8     56            0
8     9     98            0
9    10     50            0

In [13]:
# I need to get a count, store it, and slice by offset, right?
# I need to add the values to a list
# I need to store the offset in order to do this

#total_miles = df['Miles'][0] + df['Total Miles'][0]
#df['Total Miles'][0] = total_miles
#total_miles = 0

# I need to iterate over the Miles and Total Miles columns and add
tmiles = df['Total Miles']

tmiles.tail(8)
#mcount = 0
#tmcount = 0
#for i in tmiles:
#    tmiles[mcount] + tmiles[tmcount] = tmiles[i]
#    mcount = mcount + 1
#    tmcount = tmcount + 1
    
#mcount, tmcount
# can I use values?
#df2['Total Miles'].values

#df2['Total Miles'][0] = df2['Miles'][0] + df2['Miles'][1]
# checking value of df2['Total Miles'][0]

2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
Name: Total Miles, dtype: int64

In [ ]:
# I need to reference the miles column somehow
#df['Miles'][1]
ttl_miles = df2['Total Miles'][1]
ttl_miles

# how can I get Day 1[0] added to Day 2[1]
#first2 = df2['Total Miles'][0] + df2['Total Miles'][1]
#first2

In [ ]:
#df2['Miles'][0] + df2['Total Miles'][1]
df2['Miles'][0] + df2['Total Miles'][1]

In [ ]:
count = 0
for n in df2.index:
    count = count + 1
    
print ("The total could of rows is ".count)

In [ ]:
df1['Miles'].plot()